# Generated by Django 3.2.3 on 2022-01-11 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_workout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='group',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='sets',
        ),
        migrations.AddField(
            model_name='workout',
            name='bodyweight',
            field=models.CharField(default=True, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50)),
                ('sets', models.CharField(max_length=50)),
                ('reps', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.workout')),
            ],
        ),
    ]
